### ISSUE TITLE
Real-time?

### ISSUE THREAD

**Issue by ramilmsh** [shariqfarooq123/AdaBins#17]
Hi, I was doing some tests with this project and I am impressed, thank you for sharing it!

I do have a question, I was testing in colab (on a Telsa K80) and it took around .8-1.0s per image. I was wondering, do you think that with enough optimizations I could get a close-to-realtime performance on any Jetson @640x480, or is it pointless to even try? (I have not gone in depth into the code, so I don't know how much performance headroom is left)

**Comment by ialhashim** [comment]
I recommend you look at such works (https://github.com/dwofk/fast-depth) where speed is the most important factor. This work is focused on quality. Generally big models are hard to use for real-time applications.
