### ISSUE TITLE
Pre-processing on NYU dataset

### ISSUE THREAD

**Issue by luisdecker** [shariqfarooq123/AdaBins#21]
Dear authors,

I noticed that you use the official splits of the NYU Depth V2 dataset, but with the tools available from the dataset page I cannot reproduce the same kind of filenames that you use on your files.

Could you please make available the code used to preprocess the NYU Depth dataset? 

Thanks!

**Comment by shariqfarooq123** [comment]
To use the exact file names, refer to the data provided by the [BTS](https://github.com/cogaplex-bts/bts) repository.

**Comment by luisdecker** [comment]
Thanks for your help regarding the official splits, but the data that must be on "../dataset/nyu/sync/" should be obtained with which script?
