### ISSUE TITLE
Actual distance value from Depth Maps

### ISSUE THREAD

**Issue by ramanathan831** [shariqfarooq123/AdaBins#22]
Hi,
We have the Depth map values like in scales of 10-10000 for each pixel in the image. How do we find the actual distance from camera taking the picture like 5000 value on depth map corresponds to 4.5m from camera kind of thing?

**Comment by shariqfarooq123** [comment]
The output from the AdaBins model is actually the absolute depth in meters. However, depth maps are **stored** as 16-bit PNGs so we multiply with some factor first which results in the range you specified. 

For NYU this factor = 1000
For KITTI this factor = 256

Therefore, you can obtain the absolute depth in meters from the PNG data by dividing by the corresponding factor.

**Comment by PewPewLewPew** [comment]
Dear @ramanathan831 @shariqfarooq123 ,

Where were you able to obtain this 16 bit Depth map? I tried the predict_dir function in infer.py. But when reading this file with opencv i ony get values between 0 and 125.

Thank.

kr,

Bjorn
