### ISSUE TITLE
a little question on Test-set(654image) of Nyu-depth V2

### ISSUE THREAD

**Issue by calvin8899wan** [shariqfarooq123/AdaBins#25]
Sorry, I have a little question on the Test-Set with Nyu Depth V2...
I have saw "Depth Map Prediction from a Single Image using a Multi-Scale Deep Network", he mentioned that official test-set(215 scenes in the 464 scenes). but i saw many papers and official website. I didn't saw that where officially mentioned that which 215 scenes are for test which 249 scenes for training.

If you can, I hope you can answer me. Really thanks.

**Comment by shariqfarooq123** [comment]
If you want to process the data on your own, [this github repo ](https://github.com/janivanecky/Depth-Estimation/tree/master/dataset) gives detailed instructions. To get the exact setup as this project, refer to the data preparation under the [BTS repo](https://github.com/cogaplex-bts/bts).
