### ISSUE TITLE
Environment file 

### ISSUE THREAD

**Issue by VladimirYugay** [shariqfarooq123/AdaBins#31]
Hey there,

Can you please provide an environment file?

**Comment by ai-Ilike** [comment]
#8

**Comment by VladimirYugay** [comment]
Yes, I saw that issue. 
It works perfectly fine when used for inference. However, I face many problems when trying to install pytorch3d for training.

I've followed all the steps described [here](https://github.com/facebookresearch/pytorch3d/blob/master/INSTALL.md), but nothing really works. I get various errors related to CUDA (although my CUDA version is fine and it properly works with other projects).

It would be very helpful if you could provide a complete .yaml file with the environment. 

Thanks!

**Comment by GaoYann** [comment]
Hello, I encountered a similar problem with you when I installed pytorch3d on Windows system. I'd like to know how you solved it. If you have time to answer it, I'd like to thank you very much.

**Comment by VladimirYugay** [comment]
@GaoYann I have Ubuntu. Just strictly follow this [link](https://github.com/facebookresearch/pytorch3d/blob/master/INSTALL.md)!

**Comment by GaoYann** [comment]
Thank you very much. I'll try Ubuntu first.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shariqfarooq123/AdaBins"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月21日(星期三) 下午4:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shariqfarooq123/AdaBins] Environment file  (#31)





 
@GaoYann I have Ubuntu. Just strictly follow this link!
