### ISSUE TITLE
pre process of the raw data

### ISSUE THREAD

**Issue by henry123-boy** [shariqfarooq123/AdaBins#37]
hello, i want to ask something about your depth ground truth, did u densify the raw kitti depth_gt and what kind of methods did u use?

**Comment by shariqfarooq123** [comment]
No. We use raw ground truth depth maps (with missing values)

If you want to densify the depth maps anyway, you may use [Levin's colorization method](https://www.cs.huji.ac.il/w~yweiss/Colorization/) which is also used in officially inpainted NYU depth maps. 

[DenseDepth](https://github.com/ialhashim/DenseDepth) provides a [python implementation](https://gist.github.com/ialhashim/be6235489a9c43c6d240e8331836586a).
