### ISSUE TITLE
About the NYU results in paper

### ISSUE THREAD

**Issue by aaronjie** [shariqfarooq123/AdaBins#4]
Hi, first of all, thanks for your nice work and open source code. I faced a problem when evaluating the result. As list in Readme, I download the predicted depths in 16-bit format for NYU-Depth-v2 official test set and KITTI Eigen split test set from the providing link:
https://drive.google.com/drive/folders/1b3nfm8lqrvUjtYGmsqA5gptNQ8vPlzzS?usp=sharing
Then, I used the evaluation code in infer.py. In particular, I directly compared the downloaded depth maps with gt depth maps provided in NYU official split and the input size follows the eigen's center crop. The ground truth depth maps was obtained from [DenseDepth](https://github.com/ialhashim/DenseDepth)
Actually, I tried two different input size:

**input size1: 228x304 (Center cropping)**
**Results:** Metrics: {'a1': 0.895, 'a2': 0.98, 'a3': 0.997, 'abs_rel': 0.106, 'rmse': 0.419, 'log_10': 0.045, 'rmse_log': 0.131, 'silog': 9.761, 'sq_rel': 0.075}

**input size2: 45:471, 41:601** as used in your code [(line132)](https://github.com/shariqfarooq123/AdaBins/blob/main/evaluate.py#L132)
**Results:** Metrics: {'a1': 0.887, 'a2': 0.978, 'a3': 0.995, 'abs_rel': 0.11, 'rmse': 0.41, 'log_10': 0.047, 'rmse_log': 0.142, 'silog': 11.748, 'sq_rel': 0.07}

However, the absolute relative error is **0.103** in your paper. 
I can not find out the problem. Would you please help to figure it out or provide the script for reproducing the result ?

Thank you very much! :)

**Comment by shariqfarooq123** [comment]
Your "input size2" looks fine and I recommend to use the code given in evaluate.py
I will upload the evaluation instructions soon and also double-check the predictions uploaded. 

Meanwhile, Could you double-check if you're using the correct official raw data for evaluation? 
You can follow [this](https://github.com/cogaplex-bts/bts) repo to prepare the data for both training and evaluation.

**Comment by aaronjie** [comment]
> Your "input size2" looks fine and I recommend to use the code given in evaluate.py
> I will upload the evaluation instructions soon and also double-check the predictions uploaded.
> 
> Meanwhile, Could you double-check if you're using the correct official raw data for evaluation?
> You can follow [this](https://github.com/cogaplex-bts/bts) repo to prepare the data for both training and evaluation.

Hi, thanks so much for your comment. I tried and followed your suggestions and the results are consistent with results in your paper. I will go back and find the potential problem in my previous try.
Thanks again and Happy new year ! :)
Cheers!
