### ISSUE TITLE
what is focal for in train_files_with_gt.txt

### ISSUE THREAD

**Issue by ynjiun** [shariqfarooq123/AdaBins#49]
Hi @shariqfarooq123 

Very nice work!

I noticed that in both kitti and nyu train/test_files with_gt.txt there is a column of focal values.
In nyu the focal value is a constant 518.8579
But in kitti the focal values are ranging from 707.0912 to 721.856.
What is focal? Is it camera focal length? in what unit? (mm, or pixel)?
Are focal values used in training the model? 

The reason I asked these questions is if I want to train the model with my own datasets, do I need to provide focal value? if the model doesn't really use it for training/testing, could I just give an arbitrary number?

Thanks a lot for your help.

**Comment by JBYan** [comment]
I also wonder why focal value was added, did you figure it out?

**Comment by JBYan** [comment]
I also wonder why focal value was added, did you figure it out? @ynjiun 


> I noticed that in both kitti and nyu train/test_files with_gt.txt there is a column of focal values. In nyu the focal value is a constant 518.8579 But in kitti the focal values are ranging from 707.0912 to 721.856. What is focal? Is it camera focal length? in what unit? (mm, or pixel)? Are focal values used in training the model?

**Comment by shariqfarooq123** [comment]
The focal values are not used for training the AdaBins model. Its used in the [previous work ](https://github.com/cleinc/bts/) from which the dataloaders are directly taken.
