### ISSUE TITLE
issue when processing imgs with a size of (1000,750)

### ISSUE THREAD

**Issue by jucic** [shariqfarooq123/AdaBins#5]
It seems that the model doesn't support a image larger than (640,480) such as (1000,750) since in line 19 in layers.py

`embeddings = embeddings + self.positional_encodings[:embeddings.shape[2], :].T.unsqueeze(0)`

embeddings.shape[2]=713 is larger than 500 which is configured in line 14 in layers.py

`self.positional_encodings = nn.Parameter(torch.rand(500, embedding_dim), requires_grad=True)`

I tried to increase the value from 500 to 1000, however the pretrained NYU model doesn't support it, so what should I do to support an image resolution of (1000,750), do I have to adjust model parameters and then retrain the network?

**Comment by shariqfarooq123** [comment]
Unfortunately this a drawback of using learned position encodings in transformers. 

I can think of only three choices you can proceed with:

1. Simple but dumb: Just resize your images to (640,480) and then resize the predicted depth maps back to (1000,750) using bilinear interpolation.

2. Somewhat interesting: 
* Increase the number of position encodings to the size you want
* load the pretrained weights for all layers except the encodings (using a simple if check in model_io.load_checkpoint)
* Freeze the whole network and train only the encodings (should be quick enough)

3. Retrain the network from scratch

**Comment by jucic** [comment]
Thank you for your suggestions and I'll have a try with your second choice.
