### ISSUE TITLE
Loss Function on Paper

### ISSUE THREAD

**Issue by sami-automatic** [shariqfarooq123/AdaBins#51]
Thank you for sharing all of your code, this is an amazing contribution to depth society.

I would like to ask why do you add 15% of the mse instead of substracting the 85% of mse in your loss function below?
https://github.com/shariqfarooq123/AdaBins/blob/2fb686a66a304f0a719bc53d77412460af97fd61/loss.py#L24

I was curious since your paper refers to a substraction as follows:

![ss_issue](https://user-images.githubusercontent.com/18272046/143689187-41775aa2-e27d-4cda-be2c-5c9b0fcd6283.png)

Thank you for your time

**Comment by shariqfarooq123** [comment]
Thank you for your kind words.

The two formulations are equivalent by definition of variance: 

![image](https://user-images.githubusercontent.com/22071273/149846184-6073809e-fb02-4a71-9c79-f5c9a0f2932b.png)

**Comment by sami-automatic** [comment]
Thank you for your answer
