### ISSUE TITLE
How to output depth to image ?

### ISSUE THREAD

**Issue by Entretoize** [shariqfarooq123/AdaBins#55]
You give an example of how to use but it return bin_centes and predicted_depth, what to do with that ? How to export to an image ?

Thanks

**Comment by Entretoize** [comment]
I tried using `predict_dir()` but Image.fromarray doesn't seem to handle that and gives `TypeError: Cannot handle this data type: (1, 1, 480, 640), <u2`

**Comment by shariqfarooq123** [comment]
This TypeError has been [fixed](https://github.com/shariqfarooq123/AdaBins/commit/0952d91e9e762be310bb4cd055cbfe2448c0ce20)
