### ISSUE TITLE
The result of  KITTI Eigen split

### ISSUE THREAD

**Issue by guogangok** [shariqfarooq123/AdaBins#58]
We tested the predicted depths in 16-bit format for KITTI Eigen split: https://drive.google.com/drive/folders/1b3nfm8lqrvUjtYGmsqA5gptNQ8vPlzzS?usp=sharing.
The result is :
 Scaling ratios | med: 1.104 | std: 0.058

   abs_rel |   sq_rel |     rmse | rmse_log |       a1 |       a2 |       a3 | 
&   0.109  &   0.765  &   4.860  &   0.198  &   0.885  &   0.957  &   0.978  \\
Is there anything I have missed?
Thank you!

**Comment by shariqfarooq123** [comment]
That's weird. Could you please confirm you're using the official annotated depth maps downloaded from [here](http://www.cvlibs.net/download.php?file=data_depth_annotated.zip)?

**Comment by guogangok** [comment]
> That's weird. Could you please confirm you're using the official annotated depth maps downloaded from [here](http://www.cvlibs.net/download.php?file=data_depth_annotated.zip)?

Thanks for your reply!
We used the script provided by Monodepth2 to get the gt depth. (https://github.com/nianticlabs/monodepth2/blob/master/export_gt_depth.py.)
We have tested many methods in this way. It seems the gt depth is OK.

**Comment by shariqfarooq123** [comment]
You need to use accurate official annotated depth maps (that are used by our competitors at the time of publication, check, for example, [BTS](https://github.com/cleinc/bts) for fair comparison). 

It looks like you're using the RAW projected LiDAR points to get the GT. This has been shown to be very noisy (unless you do a lot of checking and filtering, which the script you provided doesn't seem to include) and sometimes leads to better numbers to methods that are worse in reality and vice-versa. See, for example, the following figure from [this](https://arxiv.org/pdf/1905.07542.pdf) paper: 

![image](https://user-images.githubusercontent.com/22071273/151945467-3e71afd0-9157-4503-9059-d01e7bd093ca.png)

**Comment by guogangok** [comment]
@shariqfarooq123  Thank you for your advice.
1) We used "https://github.com/nianticlabs/monodepth2/blob/master/export_gt_depth.py" to generate the GT from official annotated depth maps (eigen_benchmark split. 652 frames).
2) We selected the corresponding depth maps from https://drive.google.com/drive/folders/1b3nfm8lqrvUjtYGmsqA5gptNQ8vPlzzS?usp=sharing. (652 from 697)
3) We got the disparity maps using the formula: 1/(d+1e-7)
4) We evaluated the disparity maps using https://github.com/nianticlabs/monodepth2/blob/master/evaluate_depth.py ( eigen _benchmark split).
The results are:
 Scaling ratios | med: 1.050 | std: 0.051
   abs_rel |   sq_rel |     rmse | rmse_log |       a1 |       a2 |       a3 | 
&   0.083  &   0.468  &   3.974  &   0.140  &   0.926  &   0.982  &   0.993  \\
There is still a big gap. 
Evaluating different methods is really confusing.

**Comment by guogangok** [comment]
@shariqfarooq123 Thanks for your advice.
We found the cause of the problem because the predicted and GT depth maps were aligned differently.
Monodepth2 uses cv. resize to align the predicted with the GT, and this causes a big difference.
We then got the following results:

Mono evaluation - using median scaling
 Scaling ratios | med: 1.011 | std: 0.046
 abs_rel |   sq_rel |     rmse | rmse_log |       a1 |       a2 |       a3 | 
&   0.058  &   0.217  &   2.617  &   0.090  &   0.963  &   0.995  &   0.999  \\

It is not as good as the results in your paper, but it is acceptable.

And we also tested BTS, the results are:
Mono evaluation - using median scaling
Scaling ratios | med: 1.007 | std: 0.047
   abs_rel |   sq_rel |     rmse | rmse_log |       a1 |       a2 |       a3 | 
&   0.060  &   0.250  &   2.795  &   0.095  &   0.959  &   0.993  &   0.998  \\

The different ways to evaluate the SOTA methods accurately are confusing, and we need a uniform evaluation code.

Thank you again!

**Comment by shariqfarooq123** [comment]
@guogangok I agree. MDE community could really use better and stronger standards for evaluation. 

I'm glad the issue is resolved.

**Comment by nauti16** [comment]
> @shariqfarooq123 Thanks for your advice. We found the cause of the problem because the predicted and GT depth maps were aligned differently. Monodepth2 uses cv. resize to align the predicted with the GT, and this causes a big difference. We then got the following results:
> 
> Mono evaluation - using median scaling Scaling ratios | med: 1.011 | std: 0.046 abs_rel | sq_rel | rmse | rmse_log | a1 | a2 | a3 | & 0.058 & 0.217 & 2.617 & 0.090 & 0.963 & 0.995 & 0.999 \
> 
> It is not as good as the results in your paper, but it is acceptable.
> 
> And we also tested BTS, the results are: Mono evaluation - using median scaling Scaling ratios | med: 1.007 | std: 0.047 abs_rel | sq_rel | rmse | rmse_log | a1 | a2 | a3 | & 0.060 & 0.250 & 2.795 & 0.095 & 0.959 & 0.993 & 0.998 \
> 
> The different ways to evaluate the SOTA methods accurately are confusing, and we need a uniform evaluation code.
> 
> Thank you again!

@guogangok Could you please share the solution you used? I'm encountering the same issue, even though I used annotated depth maps as decribed by shariqfarooq123.

abs rel is just 0.0993
+--------+--------+--------+---------+--------+--------+----------+---------+--------+
|     a1     |     a2     |     a3     |  abs_rel |   rmse  |  log_10 | rmse_log |  silog     | sq_rel |
+--------+--------+--------+---------+--------+--------+----------+---------+--------+
|  0.8907 | 0.9692  | 0.9878  |  0.0993  | 3.6673 | 0.0426  |  0.1632    | 15.5498 | 0.6091 |
+--------+--------+--------+---------+--------+--------+----------+---------+--------+
