### ISSUE TITLE
Please add Colab demo

### ISSUE THREAD

**Issue by Aiyush-G** [shariqfarooq123/AdaBins#9]
Hi please add cola demo, cheers.

Thanks
Aiyush

**Comment by rakesh4real** [comment]
#13 does this!

**Comment by Taeyoung96** [comment]
@rakesh4real Thanks for your Colab example!  
I'm a newbie so I have another question.  
How can I get the real depth map with this Colab example?  
Where do I fix the code to get the depth map?
